[linux_lab]
cys18 ansible_host=192.168.1.68 ansible_user=cys18 ansible_python_interpreter=/usr/bin/python3 ansible_ssh_private_key_file=vault/keys/cys18
cys16 ansible_host=192.168.1.66 ansible_user=cys16
cys17 ansible_host=192.168.1.67 ansible_user=cys17

[windows_lab]
CYS18 ansible_host=192.168.1.125 ansible_user=cys10 ansible_connection=ssh ansible_shell_type=powershell ansible_ssh_private_key_file=vault/keys/CYS18
