---
- hosts: linux_clients
  become: true
  gather_facts: false
  tasks:
    - name: Shutdown Linux host
      ansible.builtin.command: shutdown -h +0
      when: inventory_hostname in target_list

- hosts: windows_clients
  gather_facts: false
  tasks:
    - name: Shutdown Windows host
      ansible.windows.win_shell: shutdown /s /t 5
      when: inventory_hostname in target_list
